- name: Copy kubelet config defaults
  ansible.builtin.copy:
    src: flannel.yml
    dest: /tmp/flannel.yml

- name: Apply flannel
  become_user: vagrant
  shell: |
    kubectl apply -f /tmp/flannel.yml