- name: Install cert packages
  apt: 
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install a list of packages
  apt:
    update_cache: yes
    pkg:
    - kubelet={{ kubernetes_version }}
    - kubeadm={{ kubernetes_version }}
    - kubectl={{ kubernetes_version }}

- name: Enable kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Disable Swap
  shell: |
    swapoff -a

- name: Ensure swap disabled after reboot
  shell: |
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes