- name: Install cert packages
  apt: 
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Creates directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0775

- name: Download file from a file path
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
    dest: /tmp/Release.key

- name: execute scripts to setup apt
  ansible.builtin.shell:
    cmd: cat /tmp/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: execute more scripts
  ansible.builtin.shell:
    cmd: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Install a list of packages
  apt:
    update_cache: yes
    pkg:
    - kubelet 
    - kubeadm
    - kubectl

- name: Enable kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Disable Swap
  shell: |
    swapoff -a && sed -i '/swap/d' /etc/fstab

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
