- name: Kubeadm Init
  shell: |
    kubeadm init --apiserver-advertise-address="192.168.56.2" --apiserver-cert-extra-sans="192.168.56.2" --pod-network-cidr=10.244.0.0/16 --control-plane-endpoint={{ node_ip }}

- name: Create kube directory
  file:
    path: /home/vagrant/.kube
    state: directory

- name: Setup kubeconfig for vagrant user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  